/* Generated by Yosys 0.60+88 (git sha1 35321cd29, clang++ 18.1.8 -fPIC -O3) */

module timer_Brtl_100000000_1000000000(clk_i, arst_i, start_i, done_o);
  input clk_i;
  wire clk_i;
  input arst_i;
  wire arst_i;
  input start_i;
  wire start_i;
  output done_o;
  wire done_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  reg busy_r = 1'h0;
  reg [6:0] cnt_r = 7'h00;
  reg start_d_r = 1'h0;
  assign _09_ = start_i & ~(start_d_r);
  assign _08_ = _09_ | busy_r;
  assign _10_ = cnt_r[0] & cnt_r[1];
  assign _11_ = cnt_r[3] | cnt_r[2];
  assign _12_ = _10_ & ~(_11_);
  assign _13_ = ~cnt_r[6];
  assign _14_ = cnt_r[4] | ~(cnt_r[5]);
  assign _15_ = _14_ | _13_;
  assign _16_ = _12_ & ~(_15_);
  assign _17_ = _16_ | cnt_r[0];
  assign _00_ = busy_r & ~(_17_);
  assign _18_ = ~(cnt_r[0] ^ cnt_r[1]);
  assign _01_ = busy_r & ~(_18_);
  assign _19_ = ~(cnt_r[0] & cnt_r[1]);
  assign _20_ = _19_ ^ cnt_r[2];
  assign _21_ = _20_ | _16_;
  assign _02_ = busy_r & ~(_21_);
  assign _22_ = ~(_10_ & cnt_r[2]);
  assign _23_ = _22_ ^ cnt_r[3];
  assign _24_ = _23_ | _16_;
  assign _03_ = busy_r & ~(_24_);
  assign _25_ = ~(cnt_r[3] & cnt_r[2]);
  assign _26_ = _10_ & ~(_25_);
  assign _27_ = ~(_26_ ^ cnt_r[4]);
  assign _28_ = _27_ | _16_;
  assign _04_ = busy_r & ~(_28_);
  assign _29_ = ~(_26_ & cnt_r[4]);
  assign _30_ = _29_ ^ cnt_r[5];
  assign _31_ = _30_ | _16_;
  assign _05_ = busy_r & ~(_31_);
  assign _32_ = ~(cnt_r[4] & cnt_r[5]);
  assign _33_ = _26_ & ~(_32_);
  assign _34_ = _33_ ^ _13_;
  assign _35_ = _34_ | _16_;
  assign _06_ = busy_r & ~(_35_);
  assign done_o = ~busy_r;
  assign _36_ = ~_16_;
  assign _07_ = busy_r ? _36_ : _09_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[0] <= 1'h0;
    else if (_08_) cnt_r[0] <= _00_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[1] <= 1'h0;
    else if (_08_) cnt_r[1] <= _01_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[2] <= 1'h0;
    else if (_08_) cnt_r[2] <= _02_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[3] <= 1'h0;
    else if (_08_) cnt_r[3] <= _03_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[4] <= 1'h0;
    else if (_08_) cnt_r[4] <= _04_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[5] <= 1'h0;
    else if (_08_) cnt_r[5] <= _05_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) cnt_r[6] <= 1'h0;
    else if (_08_) cnt_r[6] <= _06_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) busy_r <= 1'h0;
    else busy_r <= _07_;
  always @(posedge clk_i, posedge arst_i)
    if (arst_i) start_d_r <= 1'h0;
    else start_d_r <= start_i;
endmodule

(* top =  1  *)
module timer_wrapper(clk_i, arst_i, start_i, done_o);
  input clk_i;
  wire clk_i;
  input arst_i;
  wire arst_i;
  input start_i;
  wire start_i;
  output done_o;
  wire done_o;
  timer_Brtl_100000000_1000000000 u_timer (
    .arst_i(arst_i),
    .clk_i(clk_i),
    .done_o(done_o),
    .start_i(start_i)
  );
endmodule
